// Deterministic demo slate — lets the dashboard render a full MLB card set
// (varied tiers, line movement, pitcher data) when no API keys are configured.
// Numbers are illustrative, not live; the UI labels the slate as "demo".

import type { GameInput } from "./picksEngine";
import type { PitcherStats } from "./pitchers";
import type { TeamOffense } from "./ratings";

function sp(pitcher: string, ip: number, era: number, fip: number): PitcherStats {
  return { available: true, pitcher, ip, era, fip, classification: fip < 3.5 && ip >= 80 ? "ELITE" : ip < 25 ? "SPARSE" : "SOLID" };
}
function off(rpg: number, ops: number): TeamOffense {
  return { available: true, rpg, ops };
}

// fairProb pairs are derived to create a spread of edges vs the model.
export function DEMO_GAMES(dateEt: string): GameInput[] {
  return [
    {
      gameId: "demo-LAD-SF",
      gameDate: dateEt,
      gameTimeEt: "9:45 PM ET",
      venue: "Oracle Park",
      homeTeam: "SF",
      awayTeam: "LAD",
      homeTeamFull: "San Francisco Giants",
      awayTeamFull: "Los Angeles Dodgers",
      homePitcher: "Logan Webb",
      awayPitcher: "Tyler Glasnow",
      mlHome: 118,
      mlAway: -135,
      mlHomeBook: "draftkings",
      mlAwayBook: "fanduel",
      homeFairProb: 0.462,
      awayFairProb: 0.538,
      homeSpStats: sp("Logan Webb", 190, 3.25, 3.40),
      awaySpStats: sp("Tyler Glasnow", 134, 3.05, 3.12),
      homeOffStats: off(4.3, 0.712),
      awayOffStats: off(4.9, 0.794),
      openHomeMl: 110,
      openAwayMl: -120,
    },
    {
      gameId: "demo-NYY-BOS",
      gameDate: dateEt,
      gameTimeEt: "7:10 PM ET",
      venue: "Fenway Park",
      homeTeam: "BOS",
      awayTeam: "NYY",
      homeTeamFull: "Boston Red Sox",
      awayTeamFull: "New York Yankees",
      homePitcher: "Brayan Bello",
      awayPitcher: "Gerrit Cole",
      mlHome: 145,
      mlAway: -165,
      mlHomeBook: "betmgm",
      mlAwayBook: "caesars",
      homeFairProb: 0.405,
      awayFairProb: 0.595,
      homeSpStats: sp("Brayan Bello", 145, 4.10, 4.05),
      awaySpStats: sp("Gerrit Cole", 160, 2.95, 3.05),
      homeOffStats: off(4.6, 0.745),
      awayOffStats: off(4.8, 0.768),
      openHomeMl: 150,
      openAwayMl: -170,
    },
    {
      gameId: "demo-HOU-SEA",
      gameDate: dateEt,
      gameTimeEt: "10:10 PM ET",
      venue: "T-Mobile Park",
      homeTeam: "SEA",
      awayTeam: "HOU",
      homeTeamFull: "Seattle Mariners",
      awayTeamFull: "Houston Astros",
      homePitcher: "Luis Castillo",
      awayPitcher: "Framber Valdez",
      mlHome: -110,
      mlAway: -105,
      mlHomeBook: "pointsbetus",
      mlAwayBook: "betrivers",
      homeFairProb: 0.512,
      awayFairProb: 0.488,
      homeSpStats: sp("Luis Castillo", 175, 3.40, 3.55),
      awaySpStats: sp("Framber Valdez", 168, 3.15, 3.35),
      homeOffStats: off(4.2, 0.701),
      awayOffStats: off(4.5, 0.735),
      openHomeMl: -105,
      openAwayMl: -110,
    },
    {
      gameId: "demo-ATL-NYM",
      gameDate: dateEt,
      gameTimeEt: "7:20 PM ET",
      venue: "Citi Field",
      homeTeam: "NYM",
      awayTeam: "ATL",
      homeTeamFull: "New York Mets",
      awayTeamFull: "Atlanta Braves",
      homePitcher: "Kodai Senga",
      awayPitcher: "Spencer Strider",
      mlHome: 130,
      mlAway: -148,
      mlHomeBook: "draftkings",
      mlAwayBook: "fanduel",
      homeFairProb: 0.435,
      awayFairProb: 0.565,
      homeSpStats: sp("Kodai Senga", 22, 3.30, 3.40), // sparse
      awaySpStats: sp("Spencer Strider", 165, 2.85, 2.95),
      homeOffStats: off(4.4, 0.722),
      awayOffStats: off(5.0, 0.801),
      openHomeMl: 128,
      openAwayMl: -145,
    },
    {
      gameId: "demo-COL-ARI",
      gameDate: dateEt,
      gameTimeEt: "8:40 PM ET",
      venue: "Coors Field",
      homeTeam: "COL",
      awayTeam: "ARI",
      homeTeamFull: "Colorado Rockies",
      awayTeamFull: "Arizona Diamondbacks",
      homePitcher: "Kyle Freeland",
      awayPitcher: "Zac Gallen",
      mlHome: 160,
      mlAway: -180,
      mlHomeBook: "wynnbet",
      mlAwayBook: "betmgm",
      homeFairProb: 0.385,
      awayFairProb: 0.615,
      homeSpStats: sp("Kyle Freeland", 150, 4.60, 4.70),
      awaySpStats: sp("Zac Gallen", 158, 3.20, 3.30),
      homeOffStats: off(4.8, 0.758),
      awayOffStats: off(4.6, 0.740),
      openHomeMl: 155,
      openAwayMl: -175,
    },
    {
      gameId: "demo-TB-TOR",
      gameDate: dateEt,
      gameTimeEt: "7:07 PM ET",
      venue: "Rogers Centre",
      homeTeam: "TOR",
      awayTeam: "TB",
      homeTeamFull: "Toronto Blue Jays",
      awayTeamFull: "Tampa Bay Rays",
      homePitcher: "Jose Berrios",
      awayPitcher: "Shane McClanahan",
      mlHome: -120,
      mlAway: 102,
      mlHomeBook: "caesars",
      mlAwayBook: "draftkings",
      homeFairProb: 0.532,
      awayFairProb: 0.468,
      homeSpStats: sp("Jose Berrios", 170, 3.65, 3.70),
      awaySpStats: sp("Shane McClanahan", 145, 3.10, 3.20),
      homeOffStats: off(4.5, 0.731),
      awayOffStats: off(4.3, 0.715),
      openHomeMl: -118,
      openAwayMl: 100,
    },
    {
      gameId: "demo-PHI-MIA",
      gameDate: dateEt,
      gameTimeEt: "6:40 PM ET",
      venue: "loanDepot park",
      homeTeam: "MIA",
      awayTeam: "PHI",
      homeTeamFull: "Miami Marlins",
      awayTeamFull: "Philadelphia Phillies",
      homePitcher: "Jesus Luzardo",
      awayPitcher: "Zack Wheeler",
      mlHome: 138,
      mlAway: -155,
      mlHomeBook: "fanduel",
      mlAwayBook: "betmgm",
      homeFairProb: 0.418,
      awayFairProb: 0.582,
      homeSpStats: sp("Jesus Luzardo", 155, 3.55, 3.60),
      awaySpStats: sp("Zack Wheeler", 175, 3.00, 3.10),
      homeOffStats: off(4.1, 0.698),
      awayOffStats: off(4.9, 0.785),
      openHomeMl: 140,
      openAwayMl: -158,
    },
  ];
}
