// Demo soccer slate for when no Odds API key is configured.
// Uses realistic data (Brazil Série A + a World Cup opener) for UI exploration.

import type { SoccerGameInput } from "./picksEngine";

export function DEMO_SOCCER_GAMES(dateStr: string): SoccerGameInput[] {
  return [
    {
      gameId: "soccer-demo-bra-arg-001",
      gameDate: dateStr,
      gameTimeEt: "8:00 PM ET",
      venue: "Estádio do Maracanã, Rio de Janeiro",
      homeTeam: "FLA",
      awayTeam: "PAL",
      homeTeamFull: "Flamengo",
      awayTeamFull: "Palmeiras",
      leagueName: "Brazil Série A",
      leagueId: 71,
      isFriendly: false,
      isWorldCupMatchday1: false,
      homeForm: "WWLDW",
      awayForm: "WDWWL",
      mlHome: -130,
      mlDraw: 270,
      mlAway: 380,
      mlHomeBook: "draftkings",
      mlAwayBook: "fanduel",
      homeFairProb: 0.50,
      drawFairProb: 0.25,
      awayFairProb: 0.25,
      spreadHomeLine: -0.5,
      spreadHomePrice: -115,
      spreadAwayLine: 0.5,
      spreadAwayPrice: -105,
      spreadBook: "betmgm",
      totalLine: 2.5,
      totalOverPrice: -110,
      totalUnderPrice: -110,
      totalBook: "draftkings",
      openHomeMl: -120,
      openAwayMl: 350,
    },
    {
      gameId: "soccer-demo-bot-cor-002",
      gameDate: dateStr,
      gameTimeEt: "6:00 PM ET",
      venue: "Estádio Nilton Santos, Rio de Janeiro",
      homeTeam: "BOT",
      awayTeam: "COR",
      homeTeamFull: "Botafogo",
      awayTeamFull: "Corinthians",
      leagueName: "Brazil Série A",
      leagueId: 71,
      isFriendly: false,
      isWorldCupMatchday1: false,
      homeForm: "WDWLD",
      awayForm: "LLWDW",
      mlHome: -155,
      mlDraw: 290,
      mlAway: 420,
      mlHomeBook: "draftkings",
      mlAwayBook: "draftkings",
      homeFairProb: 0.55,
      drawFairProb: 0.26,
      awayFairProb: 0.19,
      spreadHomeLine: -0.5,
      spreadHomePrice: -130,
      spreadAwayLine: 0.5,
      spreadAwayPrice: 110,
      spreadBook: "betmgm",
      totalLine: 2.5,
      totalOverPrice: -115,
      totalUnderPrice: -105,
      totalBook: "fanduel",
      openHomeMl: -145,
      openAwayMl: 400,
    },
    {
      gameId: "soccer-demo-sao-flu-003",
      gameDate: dateStr,
      gameTimeEt: "5:00 PM ET",
      venue: "Morumbi Stadium, São Paulo",
      homeTeam: "SAO",
      awayTeam: "FLU",
      homeTeamFull: "Sao Paulo",
      awayTeamFull: "Fluminense",
      leagueName: "Brazil Série A",
      leagueId: 71,
      isFriendly: false,
      isWorldCupMatchday1: false,
      homeForm: "DLWWW",
      awayForm: "WWDLW",
      mlHome: 110,
      mlDraw: 255,
      mlAway: 260,
      mlHomeBook: "fanduel",
      mlAwayBook: "caesars",
      homeFairProb: 0.37,
      drawFairProb: 0.30,
      awayFairProb: 0.33,
      spreadHomeLine: 0.5,
      spreadHomePrice: -130,
      spreadAwayLine: -0.5,
      spreadAwayPrice: 110,
      spreadBook: "draftkings",
      totalLine: 2.5,
      totalOverPrice: -105,
      totalUnderPrice: -115,
      totalBook: "betmgm",
      openHomeMl: 120,
      openAwayMl: 250,
    },
    {
      gameId: "soccer-demo-atm-pal-004",
      gameDate: dateStr,
      gameTimeEt: "7:30 PM ET",
      venue: "Arena MRV, Belo Horizonte",
      homeTeam: "CAM",
      awayTeam: "RBB",
      homeTeamFull: "Atletico Mineiro",
      awayTeamFull: "Red Bull Bragantino",
      leagueName: "Brazil Série A",
      leagueId: 71,
      isFriendly: false,
      isWorldCupMatchday1: false,
      homeForm: "WWWDW",
      awayForm: "DWWLL",
      mlHome: -185,
      mlDraw: 310,
      mlAway: 520,
      mlHomeBook: "betmgm",
      mlAwayBook: "betmgm",
      homeFairProb: 0.60,
      drawFairProb: 0.25,
      awayFairProb: 0.15,
      spreadHomeLine: -1.5,
      spreadHomePrice: 120,
      spreadAwayLine: 1.5,
      spreadAwayPrice: -140,
      spreadBook: "fanduel",
      totalLine: 2.5,
      totalOverPrice: -120,
      totalUnderPrice: 100,
      totalBook: "caesars",
      openHomeMl: -175,
      openAwayMl: 500,
    },
    // World Cup opener (June 11 demo)
    {
      gameId: "soccer-demo-wc2026-001",
      gameDate: dateStr,
      gameTimeEt: "4:00 PM ET",
      venue: "AT&T Stadium, Arlington TX",
      homeTeam: "MEX",
      awayTeam: "USA",
      homeTeamFull: "Mexico",
      awayTeamFull: "United States",
      leagueName: "FIFA World Cup",
      leagueId: 1,
      isFriendly: false,
      isWorldCupMatchday1: true,
      homeForm: "WDWLW",
      awayForm: "WWLWW",
      mlHome: 120,
      mlDraw: 240,
      mlAway: 220,
      mlHomeBook: "draftkings",
      mlAwayBook: "fanduel",
      homeFairProb: 0.34,
      drawFairProb: 0.30,
      awayFairProb: 0.36,
      spreadHomeLine: 0.5,
      spreadHomePrice: -115,
      spreadAwayLine: -0.5,
      spreadAwayPrice: -105,
      spreadBook: "betmgm",
      totalLine: 2.5,
      totalOverPrice: -110,
      totalUnderPrice: -110,
      totalBook: "draftkings",
      openHomeMl: 130,
      openAwayMl: 215,
    },
    {
      gameId: "soccer-demo-wc2026-002",
      gameDate: dateStr,
      gameTimeEt: "7:00 PM ET",
      venue: "SoFi Stadium, Los Angeles",
      homeTeam: "BRA",
      awayTeam: "ARG",
      homeTeamFull: "Brazil",
      awayTeamFull: "Argentina",
      leagueName: "FIFA World Cup",
      leagueId: 1,
      isFriendly: false,
      isWorldCupMatchday1: true,
      homeForm: "WWWDW",
      awayForm: "WWWWW",
      mlHome: 220,
      mlDraw: 265,
      mlAway: -130,
      mlHomeBook: "fanduel",
      mlAwayBook: "draftkings",
      homeFairProb: 0.30,
      drawFairProb: 0.27,
      awayFairProb: 0.43,
      spreadHomeLine: 0.5,
      spreadHomePrice: -110,
      spreadAwayLine: -0.5,
      spreadAwayPrice: -110,
      spreadBook: "caesars",
      totalLine: 2.5,
      totalOverPrice: -115,
      totalUnderPrice: -105,
      totalBook: "betmgm",
      openHomeMl: 230,
      openAwayMl: -125,
    },
  ];
}
