// Soccer team tri-code normalization.
// Maps full team names (from Odds API / API-Sports) → FIFA tri-codes.

const NAME_MAP: Record<string, string> = {
  // World Cup national teams
  "Brazil": "BRA",
  "Argentina": "ARG",
  "France": "FRA",
  "Germany": "GER",
  "Spain": "ESP",
  "England": "ENG",
  "Portugal": "POR",
  "Netherlands": "NED",
  "Belgium": "BEL",
  "Croatia": "CRO",
  "Uruguay": "URU",
  "Colombia": "COL",
  "Mexico": "MEX",
  "United States": "USA",
  "Canada": "CAN",
  "Morocco": "MAR",
  "Japan": "JPN",
  "South Korea": "KOR",
  "Australia": "AUS",
  "Serbia": "SRB",
  "Switzerland": "SUI",
  "Ecuador": "ECU",
  "Senegal": "SEN",
  "Ghana": "GHA",
  "Cameroon": "CMR",
  "Tunisia": "TUN",
  "Saudi Arabia": "KSA",
  "Iran": "IRN",
  "Qatar": "QAT",
  "Denmark": "DEN",
  "Poland": "POL",
  "Wales": "WAL",
  "Costa Rica": "CRC",
  "Peru": "PER",
  "Chile": "CHI",
  "Venezuela": "VEN",
  "Paraguay": "PAR",
  "Bolivia": "BOL",
  "Panama": "PAN",
  "Honduras": "HON",
  "Guatemala": "GUA",
  "Jamaica": "JAM",
  "Trinidad and Tobago": "TRI",
  "El Salvador": "SLV",
  "Haiti": "HAI",
  "Cuba": "CUB",
  "New Zealand": "NZL",
  "Nigeria": "NGA",
  "Egypt": "EGY",
  "Algeria": "ALG",
  "Ivory Coast": "CIV",
  "Côte d'Ivoire": "CIV",
  "Mali": "MLI",
  "Guinea": "GUI",
  "Zambia": "ZAM",
  "Congo": "COD",
  "DR Congo": "COD",
  "Angola": "ANG",
  "Ethiopia": "ETH",
  "Mozambique": "MOZ",
  "Tanzania": "TAN",
  "Uganda": "UGA",
  "Zimbabwe": "ZIM",
  "Iraq": "IRQ",
  "Jordan": "JOR",
  "United Arab Emirates": "UAE",
  "Bahrain": "BHR",
  "Kuwait": "KUW",
  "Oman": "OMA",
  "Yemen": "YEM",
  "Syria": "SYR",
  "Lebanon": "LBN",
  "Palestine": "PLE",
  "China": "CHN",
  "India": "IND",
  "Indonesia": "IDN",
  "Thailand": "THA",
  "Vietnam": "VIE",
  "Philippines": "PHI",
  "Malaysia": "MAS",
  "Uzbekistan": "UZB",
  "Kazakhstan": "KAZ",
  "Ukraine": "UKR",
  "Russia": "RUS",
  "Turkey": "TUR",
  "Greece": "GRE",
  "Romania": "ROU",
  "Czech Republic": "CZE",
  "Slovakia": "SVK",
  "Hungary": "HUN",
  "Austria": "AUT",
  "Sweden": "SWE",
  "Norway": "NOR",
  "Finland": "FIN",
  "Scotland": "SCO",
  "Ireland": "IRL",
  "Albania": "ALB",
  "Bosnia and Herzegovina": "BIH",
  "North Macedonia": "MKD",
  "Montenegro": "MNE",
  "Slovenia": "SVN",
  "Bulgaria": "BUL",
  "Cyprus": "CYP",
  "Iceland": "ISL",

  // EPL clubs
  "Arsenal": "ARS",
  "Aston Villa": "AVL",
  "Bournemouth": "BOU",
  "Brentford": "BRE",
  "Brighton": "BHA",
  "Brighton & Hove Albion": "BHA",
  "Chelsea": "CHE",
  "Crystal Palace": "CRY",
  "Everton": "EVE",
  "Fulham": "FUL",
  "Ipswich": "IPS",
  "Leicester": "LEI",
  "Leicester City": "LEI",
  "Liverpool": "LIV",
  "Manchester City": "MCI",
  "Manchester United": "MUN",
  "Newcastle United": "NEW",
  "Nottingham Forest": "NFO",
  "Southampton": "SOU",
  "Tottenham Hotspur": "TOT",
  "West Ham United": "WHU",
  "Wolverhampton Wanderers": "WOL",

  // La Liga
  "Real Madrid": "RMA",
  "Barcelona": "BAR",
  "Atletico Madrid": "ATM",
  "Athletic Bilbao": "ATH",
  "Real Sociedad": "RSO",
  "Villarreal": "VIL",
  "Sevilla": "SEV",
  "Betis": "BET",
  "Real Betis": "BET",
  "Valencia": "VAL",
  "Osasuna": "OSA",
  "Celta Vigo": "CEL",
  "Rayo Vallecano": "RAY",
  "Getafe": "GET",
  "Girona": "GIR",
  "Mallorca": "MAL",
  "Cadiz": "CAD",
  "Alaves": "ALA",
  "Leganes": "LEG",
  "Valladolid": "VLD",

  // Bundesliga
  "Bayern Munich": "BAY",
  "Borussia Dortmund": "BVB",
  "RB Leipzig": "RBL",
  "Bayer Leverkusen": "LEV",
  "Eintracht Frankfurt": "SGE",
  "Wolfsburg": "WOB",
  "Freiburg": "SCF",
  "Mainz": "M05",
  "Borussia Monchengladbach": "BMG",
  "Union Berlin": "FCU",
  "Werder Bremen": "SVW",
  "Hoffenheim": "TSG",
  "Augsburg": "FCA",
  "VfB Stuttgart": "STU",
  "Heidenheim": "HDH",
  "Bochum": "BOC",
  "Holstein Kiel": "KIE",
  "St Pauli": "STP",

  // Serie A
  "Inter Milan": "INT",
  "AC Milan": "MIL",
  "Juventus": "JUV",
  "Napoli": "NAP",
  "AS Roma": "ROM",
  "Lazio": "LAZ",
  "Atalanta": "ATA",
  "Fiorentina": "FIO",
  "Torino": "TOR",
  "Bologna": "BOL",
  "Udinese": "UDI",
  "Monza": "MON",
  "Genoa": "GEN",
  "Cagliari": "CAG",
  "Lecce": "LEC",
  "Empoli": "EMP",
  "Parma": "PAR",
  "Venezia": "VEN",
  "Como": "COM",
  "Hellas Verona": "VER",

  // Brazil Série A
  "Flamengo": "FLA",
  "Palmeiras": "PAL",
  "Atletico Mineiro": "CAM",
  "Fluminense": "FLU",
  "Gremio": "GRE",
  "Internacional": "INT",
  "Corinthians": "COR",
  "Santos": "SAN",
  "Sao Paulo": "SAO",
  "Vasco da Gama": "VAS",
  "Botafogo": "BOT",
  "Bragantino": "RBB",
  "Red Bull Bragantino": "RBB",
  "Cruzeiro": "CRU",
  "Bahia": "BAH",
  "Atletico Goianiense": "ACG",
  "Fortaleza": "FOR",
  "Ceara": "CEA",
  "Sport Recife": "SPO",
  "Coritiba": "COT",
  "Vitoria": "VIT",
  "Cuiaba": "CUI",
  "Goias": "GOI",
};

/** Convert a full team name to a tri-code (falls back to first 3 uppercase chars). */
export function nameToAbbr(name: string): string {
  if (!name) return "UNK";
  const mapped = NAME_MAP[name];
  if (mapped) return mapped;
  // Fallback: first 3 uppercase letters of words
  const words = name.split(/\s+/);
  if (words.length >= 3) return words.map((w) => w[0]).join("").toUpperCase().slice(0, 3);
  return name.slice(0, 3).toUpperCase();
}
